FROM openjdk:17-alpine

# 빌드 인자 정의
ARG PROFILE
ARG JAR_PATH=build/libs/*.jar

# 기본 시스템 설정 및 의존성 설치
RUN apk update && \
    apk add redis

# 애플리케이션 JAR 복사
COPY ${JAR_PATH} /home/server.jar

# 포트 설정
EXPOSE 8080 6379

# 런타임 환경 변수 설정
ENV PROFILE=${PROFILE}

# 데이터베이스 관련 환경 변수
ARG DB_PROD_HOST
ARG DB_PROD_USERNAME
ARG DB_PROD_PASSWD
ENV DB_PROD_HOST=${DB_PROD_HOST}
ENV DB_PROD_USERNAME=${DB_PROD_USERNAME}
ENV DB_PROD_PASSWD=${DB_PROD_PASSWD}

# 소셜 로그인 관련 환경 변수
ARG SOCIAL_CLIENT_ID
ARG SOCIAL_CLIENT_PASSWD
ARG SOCIAL_CLIENT_SECRET
ENV SOCIAL_CLIENT_ID=${SOCIAL_CLIENT_ID}
ENV SOCIAL_CLIENT_PASSWD=${SOCIAL_CLIENT_PASSWD}
ENV SOCIAL_CLIENT_SECRET=${SOCIAL_CLIENT_SECRET}

# 기타 환경 변수
ARG JWT_SECRET
ARG DEFAULT_PROFILE
ARG AWS_CLOUDFRONT_DOMAIN
ARG SOCKET_SERVER_URL
ENV JWT_SECRET=${JWT_SECRET}
ENV DEFAULT_PROFILE=${DEFAULT_PROFILE}
ENV AWS_CLOUDFRONT_DOMAIN=${AWS_CLOUDFRONT_DOMAIN}
ENV SOCKET_SERVER_URL=${SOCKET_SERVER_URL}

# 엔트리포인트 설정
ENTRYPOINT sh -c "redis-server --daemonize yes && java -jar /home/server.jar"