FROM openjdk:17-alpine
ARG JAR_PATH=/build/libs/*.jar
COPY ${JAR_PATH} /home/server.jar

# 환경 변수를 ARG로 받아서 ENV로 설정합니다.
ARG PROFILE
ARG DB_PROD_HOST
ARG DB_PROD_USERNAME
ARG DB_PROD_PASSWD
ARG SOCIAL_CLIENT_ID
ARG SOCIAL_CLIENT_PASSWD

ENV PROFILE=${PROFILE}
ENV DB_PROD_HOST=${DB_PROD_HOST}
ENV DB_PROD_USERNAME=${DB_PROD_USERNAME}
ENV DB_PROD_PASSWD=${DB_PROD_PASSWD}
ENV SOCIAL_CLIENT_ID=${SOCIAL_CLIENT_ID}
ENV SOCIAL_CLIENT_PASSWD=${SOCIAL_CLIENT_PASSWD}

ENTRYPOINT ["java","-jar","/home/server.jar"]