version: '3.8'

services:
  app:
    image: ${DOCKER_HUB_USERNAME:-linkode}/${DOCKER_HUB_REPO_NAME:-linkode}:latest
    environment:
      - PROFILE=${PROFILE:-prod}
      - DB_PROD_HOST=${DB_PROD_HOST}
      - DB_PROD_USERNAME=${DB_PROD_USERNAME}
      - DB_PROD_PASSWD=${DB_PROD_PASSWD}
      - SOCIAL_CLIENT_ID=${SOCIAL_CLIENT_ID}
      - SOCIAL_CLIENT_PASSWD=${SOCIAL_CLIENT_PASSWD}
      - SOCIAL_CLIENT_SECRET=${SOCIAL_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-ap-northeast-2}
      - DEFAULT_PROFILE=${DEFAULT_PROFILE}
      - AWS_CLOUDFRONT_DOMAIN=${AWS_CLOUDFRONT_DOMAIN}
      - SOCKET_SERVER_URL=${SOCKET_SERVER_URL}
    ports:
      - "${APP_PORT:-8080}:8080"
      - "${REDIS_PORT:-6379}:6379"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3