spring:
  profiles:
    active: ${PROFILE}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION}

  cloudfront:
    domain-name: ${AWS_CLOUDFRONT_DOMAIN}


---

spring:
  config:
    activate:
      on-profile: prod
  redis:
    host: localhost
    port: 6379
---

spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
---

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${SOCIAL_CLIENT_ID}
            client-secret: ${SOCIAL_CLIENT_SECRET}

logging:
  level:
    org:
      springframework:
        web: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000  # 1 hour in milliseconds
  refresh-token-expiration: 86400000  # 1 day in milliseconds

invite:
  code:
    characters: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
    length: 6
    validity:
      minutes: 10


---

