spring:
  profiles:
    active: ${PROFILE}


---

spring:
  config:
    activate:
      on-profile: prod

---

spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379

---

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${SOCIAL_CLIENT_ID}
            client-secret: ${SOCIAL_CLIENT_SECRET}

logging:
  level:
    org:
      springframework:
        web: DEBUG

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000  # 1 hour in milliseconds
  refresh-token-expiration: 86400000  # 1 day in milliseconds


