name: Java CI/CD with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    types: [ closed ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROFILE: prod
      DB_PROD_HOST: ${{ secrets.DB_PROD_HOST }}
      DB_PROD_USERNAME: ${{ secrets.DB_PROD_USERNAME }}
      DB_PROD_PASSWD: ${{ secrets.DB_PROD_PASSWD }}
      SOCIAL_CLIENT_ID: ${{ secrets.SOCIAL_CLIENT_ID }}
      SOCIAL_CLIENT_PASSWD: ${{ secrets.SOCIAL_CLIENT_PASSWD }}
      SOCIAL_CLIENT_SECRET: ${{ secrets.SOCIAL_CLIENT_SECRET }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      WAS_HOST: ${{ secrets.WAS_HOST }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-2
      DEFAULT_PROFILE: ${{ secrets.DEFAULT_PROFILE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew --warning-mode all build -i

  docker-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (without Test)
        run: ./gradlew clean build -x test --stacktrace

      - name: Docker Hub build & push
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PWD }}
          docker build --build-arg PROFILE=${{ secrets.PROFILE }} \
          --build-arg DB_PROD_HOST=${{ secrets.DB_PROD_HOST }} \
          --build-arg DB_PROD_USERNAME=${{ secrets.DB_PROD_USERNAME }} \
          --build-arg DB_PROD_PASSWD=${{ secrets.DB_PROD_PASSWD }} \
          --build-arg SOCIAL_CLIENT_ID=${{ secrets.SOCIAL_CLIENT_ID }} \
          --build-arg SOCIAL_CLIENT_PASSWD=${{ secrets.SOCIAL_CLIENT_PASSWD }} \
          --build-arg SOCIAL_CLIENT_SECRET=${{ secrets.SOCIAL_CLIENT_SECRET }} \
          --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
          --build-arg AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }} \
          --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
          --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          --build-arg AWS_REGION=ap-northeast-2 \
          --build-arg DEFAULT_PROFILE=${{ secrets.DEFAULT_PROFILE }} \
          -t linkode/linkode:latest .
          docker images
          docker push linkode/linkode:latest

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.WAS_HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.WAS_PORT }}
          script: |
            CONTAINER_ID=$(sudo docker ps -q --filter ancestor=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO_NAME }})
            if [ ! -z "$CONTAINER_ID" ]; then
              sudo docker stop $CONTAINER_ID
              sudo docker rm $CONTAINER_ID
            fi
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO_NAME }}
            sudo docker run -d -e PROFILE=${{ secrets.PROFILE }} \
            -e DB_PROD_HOST=${{ secrets.DB_PROD_HOST }} \
            -e DB_PROD_USERNAME=${{ secrets.DB_PROD_USERNAME }} \
            -e DB_PROD_PASSWD=${{ secrets.DB_PROD_PASSWD }} \
            -e SOCIAL_CLIENT_ID=${{ secrets.SOCIAL_CLIENT_ID }} \
            -e SOCIAL_CLIENT_PASSWD=${{ secrets.SOCIAL_CLIENT_PASSWD }} \
            -e SOCIAL_CLIENT_SECRET=${{ secrets.SOCIAL_CLIENT_SECRET }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_REGION=ap-northeast-2 \
            -e DEFAULT_PROFILE=${{ secrets.DEFAULT_PROFILE }} \
            -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO_NAME }}
            
            sudo docker logs $(sudo docker ps -q --filter ancestor=${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO_NAME }})

            sudo docker image prune -f
